const programs=['AI & Machine Learning','Web Development','Data Analytics','UI / UX Design','Cloud & DevOps','Python Development'];const desc=['Python, ML concepts, AI workflows and guided project exposure.','Frontend, backend, APIs and modern web application fundamentals.','Data cleaning, visualization, reporting and insight-driven projects.','Research, wireframes, interfaces, prototypes and design thinking.','Cloud fundamentals, deployment workflows and engineering practices.','Programming foundations, automation and practical Python projects.'];document.querySelector('#programs').innerHTML=programs.map((p,i)=>`<article><div>✦</div><h3>${p}</h3><p>${desc[i]}</p><button onclick="openApply('${p}')">Apply →</button></article>`).join('');const careers=[['ENGINEERING','Software & AI Engineering','Frontend · Backend · Python · AI/ML'],['DESIGN','Product & UI/UX Design','UI Design · UX Research · Product'],['GROWTH','Marketing & Business','Digital Marketing · Sales · Partnerships'],['PEOPLE & OPS','HR & Operations','People Operations · Coordination · HR']];document.querySelector('#careerList').innerHTML=careers.map(c=>`<div class="career"><div><small>${c[0]}</small><h3>${c[1]}</h3></div><p>${c[2]}</p><button onclick="talent('${c[1]}')">Join Talent Network ↗</button></div>`).join('');const applyModal=document.querySelector('#applyModal');function openApply(p){document.querySelector('#program').value=p;applyModal.showModal()}function save(key,obj){const a=JSON.parse(localStorage.getItem(key)||'[]');a.unshift(obj);localStorage.setItem(key,JSON.stringify(a))}document.querySelector('#application').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id='APP-'+Date.now();data.date=new Date().toLocaleString();data.status='New';save('nexoraApplications',data);alert('Application submitted successfully.');e.target.reset();applyModal.close()};document.querySelector('#inquiry').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id='INQ-'+Date.now();data.date=new Date().toLocaleString();save('nexoraInquiries',data);alert('Thank you. Your inquiry has been recorded.');e.target.reset()};function talent(role){openApply('Talent Network — '+role)}function verifyCert(){const id=document.querySelector('#certId').value.trim().toUpperCase(),box=document.querySelector('#result');const certs=JSON.parse(localStorage.getItem('nexoraCertificates')||'[]');const c=certs.find(x=>x.id.toUpperCase()===id);box.className=c?'success':'error';box.innerHTML=c?`<b>✓ Verified Certificate</b><br>${c.name} · ${c.program}<br><small>${c.id} · Issued ${c.issueDate}</small>`:'Certificate not found. Please check the certificate ID.'}

// Premium scroll-reveal motion across the full site.
const revealSelectors=['.heading','.cards','.grid','.intern','.sub','.programs','.career','#verify .verify','#contact form','.tech'];revealSelectors.forEach(s=>document.querySelectorAll(s).forEach(el=>{el.classList.add((el.classList.contains('cards')||el.classList.contains('grid')||el.classList.contains('programs'))?'stagger':'reveal')}));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});document.querySelectorAll('.reveal,.stagger').forEach(el=>observer.observe(el));

// Subtle cursor parallax for the hero 3D composition on pointer devices.
const visual=document.querySelector('.visual');if(visual&&matchMedia('(pointer:fine)').matches){visual.addEventListener('mousemove',e=>{const r=visual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;visual.querySelectorAll('.float,.glass').forEach((el,i)=>{const n=(i+1)*5;el.style.marginLeft=`${x*n}px`;el.style.marginTop=`${y*n}px`})});visual.addEventListener('mouseleave',()=>visual.querySelectorAll('.float,.glass').forEach(el=>{el.style.marginLeft='0';el.style.marginTop='0'}))}

// Add a soft active state to navigation while scrolling.
const sections=[...document.querySelectorAll('main section[id]')];const links=[...document.querySelectorAll('nav a')];addEventListener('scroll',()=>{let current='';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});links.forEach(a=>{a.style.color=a.getAttribute('href')==='#'+current?'#7157ff':''})},{passive:true});