const programs=['AI & Machine Learning','Web Development','Data Analytics','UI / UX Design','Cloud & DevOps','Python Development'];const desc=['Python, ML concepts, AI workflows and guided project exposure.','Frontend, backend, APIs and modern web application fundamentals.','Data cleaning, visualization, reporting and insight-driven projects.','Research, wireframes, interfaces, prototypes and design thinking.','Cloud fundamentals, deployment workflows and engineering practices.','Programming foundations, automation and practical Python projects.'];document.querySelector('#programs').innerHTML=programs.map((p,i)=>`<article><div>✦</div><h3>${p}</h3><p>${desc[i]}</p><button onclick="openApply('${p}')">Apply →</button></article>`).join('');const careers=[['ENGINEERING','Software & AI Engineering','Frontend · Backend · Python · AI/ML'],['DESIGN','Product & UI/UX Design','UI Design · UX Research · Product'],['GROWTH','Marketing & Business','Digital Marketing · Sales · Partnerships'],['PEOPLE & OPS','HR & Operations','People Operations · Coordination · HR']];document.querySelector('#careerList').innerHTML=careers.map(c=>`<div class="career"><div><small>${c[0]}</small><h3>${c[1]}</h3></div><p>${c[2]}</p><button onclick="talent('${c[1]}')">Join Talent Network ↗</button></div>`).join('');const applyModal=document.querySelector('#applyModal');function openApply(p){document.querySelector('#program').value=p;applyModal.showModal()}function save(key,obj){const a=JSON.parse(localStorage.getItem(key)||'[]');a.unshift(obj);localStorage.setItem(key,JSON.stringify(a))}document.querySelector('#application').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id='APP-'+Date.now();data.date=new Date().toLocaleString();data.status='New';save('nexoraApplications',data);toast('Application submitted successfully.','success');e.target.reset();applyModal.close()};document.querySelector('#inquiry').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id='INQ-'+Date.now();data.date=new Date().toLocaleString();save('nexoraInquiries',data);toast('Thank you. Your inquiry has been recorded.','success');e.target.reset()};function talent(role){openApply('Talent Network — '+role)}function verifyCert(){const id=document.querySelector('#certId').value.trim().toUpperCase(),box=document.querySelector('#result');const certs=JSON.parse(localStorage.getItem('nexoraCertificates')||'[]');const c=certs.find(x=>x.id.toUpperCase()===id);box.className=c?'success':'error';box.innerHTML=c?`<b>✓ Verified Certificate</b><br>${c.name} · ${c.program}<br><small>${c.id} · Issued ${c.issueDate}</small>`:'Certificate not found. Please check the certificate ID.'}

// Premium scroll reveal with staggered sections.
const revealSelectors=['.heading','.cards','.grid','.intern','.sub','.programs','.career','#verify .verify','#contact form','.tech'];revealSelectors.forEach(s=>document.querySelectorAll(s).forEach(el=>el.classList.add((el.classList.contains('cards')||el.classList.contains('grid')||el.classList.contains('programs'))?'stagger':'reveal')));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});document.querySelectorAll('.reveal,.stagger').forEach(el=>observer.observe(el));

// Cursor-reactive hero depth.
const visual=document.querySelector('.visual');if(visual&&matchMedia('(pointer:fine)').matches){visual.addEventListener('mousemove',e=>{const r=visual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;visual.querySelectorAll('.float,.glass').forEach((el,i)=>{const n=(i+1)*7;el.style.translate=`${x*n}px ${y*n}px`});visual.querySelector('.orb').style.translate=`${x*-12}px ${y*-12}px`});visual.addEventListener('mouseleave',()=>visual.querySelectorAll('.float,.glass,.orb').forEach(el=>el.style.translate='0 0'))}

// Active navigation state.
const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('nav a')];addEventListener('scroll',()=>{let current='';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});

// Reading progress indicator.
const progress=document.createElement('div');progress.className='scroll-progress';document.body.appendChild(progress);addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max?scrollY/max:0})`},{passive:true});

// Ambient cursor glow for desktop.
if(matchMedia('(pointer:fine)').matches){const glow=document.createElement('div');glow.className='cursor-glow';document.body.appendChild(glow);addEventListener('pointermove',e=>{glow.style.transform=`translate(${e.clientX}px,${e.clientY}px)`},{passive:true})}

// Magnetic primary actions.
document.querySelectorAll('.primary,.pill,button').forEach(btn=>{if(!matchMedia('(pointer:fine)').matches)return;btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;btn.style.translate=`${x*.08}px ${y*.12}px`});btn.addEventListener('mouseleave',()=>btn.style.translate='0 0')});

// 3D tilt for cards while preserving touch usability.
if(matchMedia('(pointer:fine)').matches){document.querySelectorAll('.cards article,.grid article,.programs article').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),rx=((e.clientY-r.top)/r.height-.5)*-5,ry=((e.clientX-r.left)/r.width-.5)*7;card.style.transform=`perspective(800px) rotateX(${rx}deg) rotateY(${ry}deg) translateY(-7px)`});card.addEventListener('mouseleave',()=>card.style.transform='')})}

// Lightweight toast feedback instead of blocking alerts.
function toast(message,type=''){let t=document.querySelector('.nexora-toast');if(!t){t=document.createElement('div');t.className='nexora-toast';document.body.appendChild(t)}t.textContent=message;t.dataset.type=type;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),3200)}

// Keyboard-friendly certificate verification.
const certInput=document.querySelector('#certId');if(certInput)certInput.addEventListener('keydown',e=>{if(e.key==='Enter')verifyCert()});

// Close modal by clicking its backdrop.
applyModal.addEventListener('click',e=>{const r=applyModal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)applyModal.close()});